- name: apply terraform configuration
  terraform:
    project_path: "{{ iaas_tf_dir }}/aws/"
    state: "{{ tf_action | default('present') }}"
  register: result
  tags: aws
- name: result of terraform run
  debug:
    var: "result.stdout_lines"
  tags: aws
