- name: Libvirt provider checkums are downloaded
  get_url:
    url: "{{ iaas_tf_libvirt_provider_url }}v{{ iaas_tf_libvirt_provider_version }}/terraform-provider-libvirt-{{ iaas_tf_libvirt_provider_version }}.sha256"
    dest: /tmp/libvirt_provider.sha256

- name: Libvirt provider tarball url is found
  set_fact:
    tarball_name: "{{ item }}"
  with_lines: grep 'Ubuntu_18.04.amd64.tar' /tmp/libvirt_provider.sha256 | awk '{ print $2 }'

- name: Libvirt provider tarball is downloaded
  get_url:
    url: "{{ iaas_tf_libvirt_provider_url }}v{{ iaas_tf_libvirt_provider_version }}/{{ tarball_name }}"
    dest: /tmp/libvirt_provider.tar.gz
    checksum: "{{ item }}"
  with_lines: echo "sha256:"$(grep 'Ubuntu_18.04.amd64.tar' /tmp/libvirt_provider.sha256 | awk '{ print $1 }')

- name: Libvirt provider tarball is extracted
  unarchive:
    src: /tmp/libvirt_provider.tar.gz
    dest: /tmp/

- name: Terraform directory exists
  file:
    state: directory
    path: "~/.terraform.d/plugins"

- name: Provider executable is in terraform directory
  copy:
    src: /tmp/terraform-provider-libvirt
    dest: "~/.terraform.d/plugins/terraform-provider-libvirt_v{{ iaas_tf_libvirt_provider_version }}"
    mode: '0755'
